/race2_auv/mvp_control_ros_node:
  ros__parameters:
    generator_type: tf
    control_frequency: 5.0
    enabled: false
    # cg_link: cg_link
    # cg_link: float_cg_link
    # world_link: world_ned
    child_link_initial: cg_link
    world_link_initial: world_ned
    controller_no_setpoint_timeout: 2.0