/race2_auv/imu_driver_node:
    ros__parameters:
      roll_offset: 3.1415926
      pitch_offset: 0.0
      yaw_offset: 1.5707
      roll_reverse: 1.0
      pitch_reverse: -1.0
      yaw_reverse: -1.0

/race2_auv/thruster_driver_node:
    ros__parameters:
      thruster_pub_topic: /race2_auv/stonefish/thruster_command
      thruster_length: 4
      thruster_sub_topics: [/race2_auv/control/thruster/sway, 
                          /race2_auv/control/thruster/heave_bow, 
                          /race2_auv/control/thruster/surge_port, 
                          /race2_auv/control/thruster/surge_starboard]

/race2_auv/servo_driver_node:
    ros__parameters:
      servo_pub_topic: /race2_auv/stonefish/servo/desired_joint_states
      servo_length: 2
      servo_sub_topics: [/race2_auv/control/surge_port_servo, 
                         /race2_auv/control/surge_starboard_servo]
      servo_joint_names: [race2_auv/surge_port_servo_joint, 
                          race2_auv/surge_starboard_servo_joint]
/race2_auv/dvl_driver_node:
    ros__parameters:
      dvl_in: /mvp2_test_robot/dvl/stonefish/raw
      dvl_out: /mvp2_test_robot/dvl/twist
      dvl_alt_out: /mvp2_test_robot/dvl/altitude